exit:
  name: "Gated Cell Population Data Upload"
  active: True
  type: "Local"
  endpoint: "/mount/fs/pipeline1"
  order: 2
image: "pic.jpg"
subtitle: "YYY"
tags:
  - "tag-3"
  - "this is a long tag"
group: "Flow Cytometry"
order: 5