exit:
  name: "Gated Cell Population Data Upload"
  active: False
  type: "Local"
  endpoint: "/mount/fs/pipeline1"
  order: 2
image: "pic.jpg"
tags:
  - "tag-3"
  - "this is a long tag"
group: "CSV Converter"
order: 5