exit:
  name: "Gated Cell Population Data Upload"
  active: False
  type: "local_json"
  endpoint: "/mount/fs/pipeline1"
  order: 2
image: "pic.jpg"
subtitle: 
tags:
  - "tag-1"
  - "this is a long tag"
group:
order: 2